.TH LIBCALCULATORFINANCE 1 libcalculatorfinance\-VERSION
.SH NAME
libcalculatorfinance \- a shared library, written in C for doing financial calculations
.SH SYNOPSIS
.B libcalculatorfinance
.SH DEPENDS ON
A c-compiler that supports the C99 standard.
.SH DESCRIPTION
libcalculatorfinance is a c library, that contains functions for making financial calculations.
It can be used for calculations regarding money management in trading, investing or keeping financial records.
.SH OPTIONS
.TP
.B Somefunc
Comment for Somefunc
.SH USAGE
.SH SEE ALSO
.SH BUGS
None that I know of. All unit-tests succeeded, upon creation of the library.
.SH EXAMPLES
TBD
