# Makefile

main: main.c calculator_finance.c unit_test.c general_functions.c
	cc -W -Wall -Werror -Wextra -o calculator_finance main.c calculator_finance.c unit_test.c general_functions.c


clean:
	rm -rfv calculator_finance *.o
