= LIBCALCULATORFINANCE(1)
:doctype: manpage

== NAME
libcalculatorfinance - a shared library, written in C for doing financial calculations

== SYNOPSIS
Installed version: libcalculatorfinance-VERSION +

Installed as: *libcalculatorfinance.so*

== DEPENDS ON
A c-compiler that supports the C99 standard or higher.

== DESCRIPTION
libcalculatorfinance is a c library, that contains functions for making financial calculations.
It can be used for calculations regarding money management in trading, investing or keeping financial records.

== FUNCTIONS

*char *version();* +
Returns a string with the library version.

*double calculate_average_price(int a_nargs, ...);* +
calculate_average_price: +
Calculate the average price, based on previous transactions. +
It requires a SharesPrice struct list, preceded by the total number
of records.

....
Note:
S1 = 415, P1 = 23.65, S2 = 138, P2 = 16.50
When you need to buy new stocks and you need to log this for
accounting purposes, you need to know what the average price was
that you paid. You only know the total number of shares you have,
called S3. The price is the average of all prices you paid on buy/
sell of all previous transactions.
S1 * P1 + S2 * P2 = S3 * P3
=> P3 = (S1 * P1 + S2 * P2) / (S1 + S2)
=> P3 = (415 * 23.65 + 138 * 16.50) / 553
=> P3 = 21.8657
....

*double calculate_percentage_of(double a_value, double a_from_value);* +
Calculate what percentage a_value is from a_from_value.

*double convert_from_orig(double a_price, double a_exchange_rate);* +
Returns a price, with an exchange rate applied to it. +
Used to convert a given currency to a new currency.

*double convert_to_orig(double a_converted_price, double a_exchange_rate);* +
Returns a price in the original currency, with the exchange rate no longer applied to it.

*int calculate_shares_recommended(double a_pool, double a_commission, double a_tax, double a_price);* +
Calculates the recommended amount of shares you can buy.

*int calculate_leveraged_contracts(int a_n);* +
Calculates the number of contracts to buy, according to an algorithm that determines an ideal amount of leverage.

*double calculate_stoploss(double a_price, int a_shares, double a_tax, double a_commission, double a_risk, double a_pool, int a_is_long);* +
Calculates the stoploss.

....
Long:
amount selling at stoploss - amount at buying = initial risk of pool
(S.Pb + S.Pb.T + C) - (S.Ps - S.Ps.T - C) = R/100 * pool
Short:
amount selling - amount buying at stoploss = initial risk of pool
(S.Psl + S.Psl.T + C) - (S.Ps - S.Ps.T - C) = R/100 * pool
....

*double calculate_risk_input(double a_pool, double a_risk);* +
Calculates the risk based on total pool and input. +
Consider this the theoretical risk we want to take.

*double calculate_risk_initial(double a_price, int a_shares, double a_tax, double a_commission, double a_stoploss, int a_is_long);* +
Calculates the initial risk. +
This is the risk we will take if our stoploss is reached. +
This should be equal to the risk_input if everything was correctly calculated.

....
Long:
S.Pb + S.Pb.T + C - (S.Psl - S.Psl.T - C)
Short:
S.Ps + S.Psl.T + C - (S.Ps - S.Ps.T - C)
....

*double calculate_amount(double a_price, int a_shares);* +
Calculates the amount without tax and commission.

*double calculate_amount_with_tax_and_commission(double a_price, int a_shares, double a_tax, double a_commission, transaction_type_t a_transaction_type);* +
Calculates the amount, including tax and commission.

....
Note:
AMT = SP + SPT + C (buy)
AMT = SP - SPT - C (sell)
....

*double calculate_amount_with_tax(double a_price, int a_shares, double a_tax, transaction_type_t a_transaction_type);* +
Calculates the amount (buy/sell) with tax included, but not the commission.

....
Note:
profit_loss = S.P + S.P.T (buy)
profit_loss = S.P - S.P.T (sell)
....

*double cost_transaction(double a_price, int a_shares, double a_tax, double a_commission);* +
Cost of transaction (tax and commission).

*double cost_tax(double a_amount, double a_commission, int a_shares, double a_price, transaction_type_t a_transaction_type);* +
Cost of tax (buy and sell).

*double calculate_price(double a_amount, int a_shares, double a_tax, double a_commission, transaction_type_t a_transaction_type);* +
Calculates the price when buying or selling.

*double calculate_risk_actual(double a_price_buy, int a_shares_buy, double a_tax_buy, double a_commission_buy, double a_price_sell, int a_shares_sell, double a_tax_sell, double a_commission_sell, double a_risk_initial, double a_profit_loss);* +
Calculates the risk we actually took, based on the data in TABLE_TRADE.

....
Note:
risk_actual = S.Pb + S.Pb.T + Cb - (S.Ps - S.Ps.T - Cs)
It's the same for long and short.
....

*double calculate_r_multiple(double a_profit_loss, double a_risk_initial);* +
Function to calculate R-multiple.

*double calculate_cost_total(double a_amount_buy, double a_tax_buy, double a_commission_buy, double a_amount_sell, double a_tax_sell, double a_commission_sell);* +
Function to calculate the total cost associated with the given trade.

*double calculate_profit_loss(double a_price_buy, int a_shares_buy, double a_price_sell, int a_shares_sell);* +
Calculates the profit_loss, without taking tax and commission into account.

....
Note:
profit_loss = S.Ps - S.Pb
It's the same for long and short.
....

*double calculate_profit_loss_total(double a_price_buy, int a_shares_buy, double a_tax_buy, double a_commission_buy, double a_price_sell, int a_shares_sell, double a_tax_sell, double a_commission_sell);* +
Calculates the total profit_loss.

....
Note:
profit_loss = S.Ps - S.Ps.T - C - (S.Pb + S.Pb.T + C)
It's the same for long and short.
....

*double calculate_cost_other(double a_profit_loss, double a_profit_loss_total, double a_cost_total);* +
Calculates other costs based on the difference that remains.

== USAGE
It's a library, designed to be used from application code. +
See the EXAMPLES section on how to use it in python.

== SEE ALSO
This library stands on it's own and is not related to other man pages.

== BUGS
None that I know of. All unit-tests succeeded, upon creation of the library.

== EXAMPLES
Python +
To use this in python, you can load the library as shown in the following examples.

[source,python]
----
from ctypes import cdll
lcf = cdll.LoadLibrary('libcalculatorfinance.so')
print(lcf.calculate_leveraged_contracts(5))
----

For the function _double calculate_average_price(int a_nargs, ...);_
you need a SharesPrice struct, which is defined in C as: +
[source,c]
----
typedef struct
{
    int sp_shares;
    double sp_price;
} SharesPrice;
----

To use this struct from python, you would need to declare the following: +
[source,python]
----
from ctypes import cdll
from ctypes import Structure, c_int, c_double

lcf = cdll.LoadLibrary('libcalculatorfinance.so')

class SharesPrice(Structure):
     _fields_ = [
        ("sp_shares", c_int),
        ("sp_price", c_double)]

l_sharesprice1 = SharesPrice(153, 12.18)
l_sharesprice2 = SharesPrice(240, 23.65)
print(lcf.calculate_average_price(2, byref(l_sharesprice1), byref(l_sharesprice2)))
----
