/* See LICENSE file for copyright and license info. */

#define FILE_IVE_LAYOUT "gp_income_vs_expenses.gnu"


static int prepare_temp_file(
    char *a_input_file,
    FILE *a_output_file,
    int a_start_year,
    int a_end_year
);

static char *f_cmd_income_vs_expenses =
    "ledger -f %s bal --real -X EUR -s -p %d -d \"T&l<=1\" expenses income | grep -Eo '[0-9\\.]{1,100}'";


/*
 * prepare_temp_file:
 * This function prepares the data to be plotted,
 * in a temporary file that can be read by gnuplot.
 */
static int prepare_temp_file(
    char *a_input_file,
    FILE *a_output_file,
    int a_start_year,
    int a_end_year
)
{
    int l_records;
    int i;
    FILE *l_fp;
    char l_cmd[INPUT_LINE_MAX];
    char l_line_temp[INPUT_LINE_MAX];
    char l_line_input[INPUT_LINE_MAX];
    char l_line_output[INPUT_LINE_MAX]; /* The output line may be just as long. */
    double l_d1;
    double l_d2;
    double l_d3;
    char *l_tmp;
    char l_current_datetime[20];
    int l_current_year;

    l_records = (a_end_year - a_start_year);    
    l_current_year = a_start_year - 1;
    for (i = 0; i <= l_records; i++)
    {   
        l_current_year += l_records;
        sprintf(l_cmd, f_cmd_income_vs_expenses, a_input_file, l_current_year);
        l_fp = popen(l_cmd, "r");
        if (l_fp == NULL)
        {
            fprintf(stderr, "Could not execute ledger command.\n");
            exit(1);
        }

        *l_line_output = '\0';
        while (fgets(l_line_input, INPUT_LINE_MAX, l_fp) != NULL)
        {
            *l_line_temp = '\0'; /* Make sure temp string is empty. */
            trim_whitespace(l_line_temp, l_line_input, INPUT_LINE_MAX);
            if (strlen(l_line_output) <= 0)
            {
                sprintf(l_line_output, "%s", l_line_temp);
            }
            else
            {
                sprintf(l_line_output, "%s %s", l_line_output, l_line_temp);
            }
        }
        l_d1 = strtod(l_line_output, &l_tmp);
        l_d2 = strtod(l_tmp, &l_tmp);
        l_d3 = strtod(l_tmp, NULL);
        //printf("test: l_d1 = %.2f, l_d2 = %.2f, l_d3 = %.2f\n", l_d1, l_d2, l_d3);
        
        if (pclose(l_fp) == -1)
            fprintf(stderr, "Error reported by pclose().\n");
        
        /* Initialize tmp file */    
        if (i == 0) 
        {
            // TODO: move timestamp function in its own module.
            // TODO: make format an enum?
            timestamp(l_current_datetime, "%02d%02d%02d_%02d%02d%02d", sizeof(l_current_datetime));
            fprintf(a_output_file, "# Generated by ledgerplot %s on %s.\n", VERSION, l_current_datetime);
            fprintf(a_output_file, "year expenses income difference\n");
        }
        /* Write data to tmp file */
        // TODO: check if we need to perform operations on these values?
        fprintf(a_output_file, "%d %.2lf %.2lf %.2lf\n", l_current_year, l_d1, l_d2, l_d3); 
    }
    return 0;
}
